# Generated by Django 5.0 on 2026-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('license_no', models.CharField(max_length=50)),
                ('plate_no', models.CharField(max_length=30)),
                ('toda_no', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('photo_license', models.TextField(blank=True, null=True)),
                ('photo_plate', models.TextField(blank=True, null=True)),
                ('photo_toda', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('verified_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commuter_id', models.BigIntegerField()),
                ('pickup_location', models.TextField()),
                ('destination', models.TextField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rides',
                'managed': False,
            },
        ),
    ]
