# Generated by Django 6.0.2 on 2026-05-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FareConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=8)),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('surge_enabled', models.BooleanField(db_column='surge_active', default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fare_config',
                'managed': False,
            },
        ),
    ]
