spring.application.name=FinalProject

# ===============================
# DATABASE / FLYWAY CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5434/auth_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

spring.jpa.hibernate.ddl-auto=update

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=Zm9ydHktdHdvLWlzLXRoZS1hbnN3ZXItdG8tbGlmZS10aGUtdW5pdmVyc2UtYW5kLWV2ZXJ5dGhpbmc=
jwt.expiration=86400000
jwt.cookie.domain=

# ===============================
# EMAIL / SMTP CONFIG (Gmail)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# DEVTOOLS / DOCKER OPTIMIZATION
# ===============================
spring.devtools.restart.enabled=true

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=INFO

# MongoDB
spring.data.mongodb.uri=mongodb://mongodb:27017/pasadanow_chat
spring.data.mongodb.host=mongodb
spring.data.mongodb.port=27017
spring.data.mongodb.database=pasadanow_chat
google.client.id=509923494008-qr2n8die1rinopp4kh30c6drdidcalro.apps.googleusercontent.com